mysite/books/urls.py

from django import views
from django.urls import path
from .views import *

# užkrauna puslapį
urlpatterns = [
    path('', index, name='index'),
    path('info/', info, name='info'),
    path('authors/', authors, name='authors'),
    path('login/', login, name='login'),
    path('logged_out/', logged_out, name='logged_out'),
    path('register/', register, name='register'),
    path('password_reset/', password_reset, name='password_reset'),
    path('search/', search, name='search'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from mysite import settings
from django.views.generic import RedirectView
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

# užkrauna puslapį
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
    path('tinymce/', include('tinymce.urls')),
    path(r'^i18n/', include('django.conf.urls.i18n')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/books/models.py
from django.db import models
from django.views.generic import *
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.urls import reverse

# Create your models here.

class Books(models.Model):
    book_title = models.CharField(max_length=150, verbose_name = 'Knygos pavadinimas')
    publisher = models.CharField(max_length=50, verbose_name = 'Išleista (metai)')
    pages = models.CharField(max_length=10, verbose_name = 'Puslapiai')
    language = models.CharField(max_length=50, verbose_name = 'Kalba')
    book_image = models.ImageField(upload_to="images/")
    authorAdd = models.ForeignKey('BookAuthor', on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.book_title
    
    class Meta:
        verbose_name = 'Knygos'
        verbose_name_plural = 'Knygos'
        ordering = ['book_title', ]

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
class BookAuthor(models.Model):
    full_name = models.CharField(max_length=100, verbose_name = 'Autoriaus vardas, pavardė')
    country = models.CharField(max_length=50, verbose_name = 'Šalis')
    about_author = models.TextField(blank=True, verbose_name = 'Apie autorių')
    photo = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name = 'Autorius'
        verbose_name_plural = 'Autoriai'
        ordering = ['full_name', ]


# komentarų modelis
class BookReview(models.Model):
    book = models.ForeignKey('Books', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=1000)

    class Meta:
        verbose_name = 'Knygų atsiliepimai'
        verbose_name_plural = 'Knygų atsiliepimai'

mysite/books/forms.py
from .models import BookReview
from django import forms

class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer',)
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

mysite/books/views.py

from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import *
from django.views import generic
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.db.models import Q
from django.views import*
from django.views.generic import *
from .forms import BookReviewForm
from django.views.generic.edit import FormMixin
from django.urls import reverse

# Create your views here.

menu = [{'title': "Pradžia", 'url_name': "index"},
        {'title': "Knygų rekomendacijos", 'url_name': "info"},
        {'title': "Autoriai", 'url_name': "authors"}
]

# pagrindinis puslapis
def index(request):
    books_count = Books.objects.count()
    book_author_count = BookAuthor.objects.count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'menu': menu,  
        'title': 'Rekomenduokite knygą!',
        'books_count': books_count,
        'book_author_count': book_author_count,
        'num_visits': num_visits
    }
    return render(request, 'books/index.html', context=context)

# knygų informacijos puslapis (Rekomenduotinų knygų psl.)
def info(request):
    allbooks = Books.objects.all()
    context = {
        'allbooks': allbooks,
        'menu': menu,        
        'title': 'Knygų sąrašas',
        'title2': 'Rekomenduotinų knygų sąrašas'
    }
    return render(request, 'books/info.html', context=context)

# apie autorius
def authors(request):
    allauthors = BookAuthor.objects.all()
    context = {
        'allauthors': allauthors,
        'menu': menu,        
        'title': 'Knygų autoriai',
        'title2': 'Apie knygų autorius'
    }
    return render(request, 'books/authors.html', context=context)

# prisijungimas
def login(request):
    context = {
        'menu': menu,        
        'title': 'Prisijungimas',
    }
    return render(request, 'books/registration/login.html', context=context)

# atsijungimas
def logged_out(request):
    context = {
        'menu': menu,        
        'title': 'Atsijungti',
    }
    return render(request, 'books/logged_out.html', context=context)

# slaptažodžio atstatymas
def password_reset(request):
    context = {
        'menu': menu,        
    }
    return render(request, 'books/password_reset_form.html', context=context)


# vartotojo registracija
@csrf_protect
def register(request):
    context = {
        'menu': menu,        
        'title': 'Registracija',
    }
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
        messages.error(request, f'Vartotojas užregistruotas! Galite prisijungti.')
    return render(request, 'books/register.html', context=context)

# paieška
def search(request):
    query = request.GET.get('query')
    search_results = Books.objects.filter(Q(book_title__icontains=query) | Q(language__icontains=query))
    return render(request, 'books/search.html', {'books': search_results, 'query': query})

# atsiliepimai
class BookDetailView(FormMixin, generic.DetailView):
    model = Books
    template_name = '/books/info.html'
    form_class = BookReviewForm

    class Meta:
        ordering = ['book_title']

    def get_success_url(self):
        return reverse('books/info', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(BookDetailView, self).form_valid(form)
    

mysite/books/templates/books/add_book_form.html
{% extends 'books/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Naujas knygos egzempliorius</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>


{% endblock %}

mysite/books/templates/books/authors.html
{% extends 'books/base.html' %}
{% block content %}

<br>
<div class="container mt-1">
<h4>{{ title2 }}</h4>

<form class="form-inline my-2 my-lg-0" style="display:flex;">
  <input class="form-control mr-sm-2" type="search" placeholder="Ieškoti" />
  <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" style="margin-left: 10px;"> Ieškoti </button>
</form>

<div class="row">
  {% for q in allauthors %}
    <div class="card" style="margin: 10px; display:flex;" >
      <img class="rounded" src="{{q.photo.url}}" alt="Card image cap" height="auto" width="200" style="margin-top: 10px;">
      <div class="card-body">
        <h5 class="card-title">{{q.full_name}}</h5>
        <p class="card-text">{{q.about_author}}</p>
        <!-- <a href="#" class="btn btn-primary" style="background-color: rgb(165, 164, 164); border:rgb(221, 220, 220)">Žiūrėti autoriaus knygas</a> -->
      </div>
    </div>
  {% endfor %}
</div>
</div>




{% endblock %}

mysite/books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="shortcut icon" href="{% static 'books/images/books_logo.ico' %}" type="image/x-icon" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="{% static 'books/css/styles.css' %}"/>
  <title>{{ title }}</title>
</head>

<body>
  {% block mainmenu %}

  <nav class="navbar sticky-top navbar-expand-sm navbar-light" name="mainmenu" style="background-color: #a8b0b6; width: 100%;">
    <div class="container-fluid">
      <ul class="navbar-nav list-inline">
        {% for x in menu %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url x.url_name %}" style="color: #fff;"> {{ x.title }} </a>
        </li>
        {% endfor %}

        {% if user.is_authenticated %}
        <li class="nav-item" style="margin-left: 1050px;"><a class="nav-link" href="#">
          <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
          </svg>
        {{ user.get_username }}</a></li>
      
        <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Atsijungti</a></li>
        {% else %}
        <li class="nav-item" style="margin-left: 1050px;"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
      {% endif %}
      </ul>
    </div>
  </nav>


  {% endblock %} {% block content %} {% endblock %}
<div class="container mt-1">
  <footer style="color: rgb(112, 112, 112); text-align: center;"><p>Autorinės teisės © 2023, Vilma Čivilytė</p></footer>  
</div>
</body>

</html>

mysite/books/templates/books/index.html
{% extends 'books/base.html' %}

{% block content %}

<br>
<div class="container mt-3">

    <h4 style="font-family:verdana; text-align:center;"> Rekomenduokite perskaityti knygą! </h4>
    <div class="container mt-3">
        <img src="https://nuotraukos.mediakatalogas.lt/thumbs/book-2265490_1280.jpg" alt="Knyga pagrindiniame"
            width="500" height="272" id="booksmain" name="booksmain"
            style="border-radius: 15%; box-shadow: 10px; text-align:center" class="mx-auto d-block">
    </div>
    <br>
    <h6 style="text-align: center;">Puslapis skirtas dalintis patirtimi apie perskaitytą knygą ir ją rekomenduoti kitiems.</h6>
    <hr>
</div>
<br>
<div class="container mt-3" style="height: 50%; width: 25%; border: 1px solid rgb(175, 174, 174); border-radius: 10px; padding: 20px; margin-left:30px">
    <h6>Puslapio statistika:</h6>
    <p>Rekomenduotinų knygų skaičius: {{ books_count }}</p>
    <p>Knygų autorių skaičius: {{ book_author_count }}</p>
    <p>Šioje svetaineje apsilankė {{ num_visits }} lankytojų(/-ai).</p>
</div>
<br>


{% endblock %}

mysite/books/templates/books/info.html
{% extends 'books/base.html' %}
{% block content %}

<br>
<div class="container mt-1">
    <h4>{{ title2 }}</h4>

    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-lg-0" style="display:flex;">
        <input name="query" class="form-control mr-sm-2" type="text" placeholder="Ieškoti" />
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" style="margin-left: 10px;"> Ieškoti
        </button>
    </form>


    <div class="row">
        {% for a in allbooks %}
        <div class="card" style="margin: 10px;">
            <div class="container" style="margin-top: 15px;">
                <div class="row">
                    <div class="col-sm">
                        {% if a.book_image %}
                        <p><img class="rounded" src="{{a.book_image.url}}" height="300" width="auto"></p>
                        {% endif %}
                    </div>
                    <div class="col-sm">
                        <p> Autorius: {{ a.authorAdd }}</p>
                        <p> Pavadinimas: <strong>{{ a.book_title }}</strong></p>
                        <p> Išleidimo metai: {{ a.publisher }}</p>
                        <p> Puslapiai: {{ a.pages }}</p>
                        <p> Kalba: {{ a.language }}</p>
                    </div>
                    <hr>
                    <div class="col-sm">
                        <div class="col-sm">
                            <h5>Atsiliepimai</h5>
                            {% if book.bookreview_set.all %}
                                {% for review in book.bookreview_set.all %}
                                    <hr>
                                    <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created }}</em>
                                    <p>{{ review.content }}</p>
                                {% endfor %}
                            {% else %}
                            <p>Knyga neturi atsiliepimų.</p>
                            {% endif %}
                        </div>
                        <div class="col-sm">
                            {% if user.is_authenticated %}
                            <div class="fieldWrapper">
                                <hr>
                                <h5>Jūsų atsiliepimas:</h5>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="text" value="{{ form.content }}" style="width: 20%; height:30px">
                                    <br>
                                    <input type="submit" class="btn btn-secondary" style="margin-bottom: 10px; margin-top: 10px;"
                                        value="Palikti atsiliepimą">
                                </form>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

mysite/books/templates/books/logged_out.html
{% extends 'books/base.html' %}

{% block content %}

<p>Sėkmingai atsijungėte!</p>  
<a href="/login">Prisijungti iš naujo.</a>

{% endblock %}

mysite/books/templates/books/register.html
{% extends 'books/base.html' %}
{% block content %}

<br>
<div class="container mt-1">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h4 align="center"> {{ title }} </h4>
            <hr>

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class="container mt-1">
                <form method="POST">
                    {% csrf_token %}
                        <div class="form-group mt-3">
                            <label for="username">Vartotojo vardas</label>
                            <input name="username" type="text" class="form-control" id="username"
                                aria-describedby="usernameHelp">
                            <small id="usernameHelp" class="form-text text-muted">Iki 50 simbolių.</small>
                        </div>
                        <div class="form-group mt-3">
                            <label for="exampleInputEmail1">Elektroninis paštas</label>
                            <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                            <small id="emailHelp" class="form-text text-muted"></small>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password">Slaptažodis</label>
                            <input name="password" type="password" class="form-control" id="password"
                                aria-describedby="pwdHelp">
                            <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti
                                vien tik
                                skaičiai</small>
                        </div>
                        <div class="form-group mt-3">
                            <label for="password2">Pakartoti slaptažodį</label>
                            <input name="password2" type="password" class="form-control" id="password2"
                                aria-describedby="pwd2Help">
                        </div>
                        <div class="form-group mt-3">
                            <button type="submit" class="btn btn-secondary register-button"> Prisiregistruoti </button>
                        </div>
                        <div class="form-group mt-3">
                            <p align="center"><br><span>Grįžti į <a href="{% url 'login'%}">prisijungimą. </a></span></p>
                        </div>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>


{% endblock %}

mysite/books/templates/books/search.html
{% extends 'books/base.html' %}

{% block content %}
</br>
<h3>Paieškos pagal "{{query}}" rezultatai:</h3>
  </br>
  {% if allbooks %}
  <ul>
    {% for books in allbooks %}
      <li>
        <a href="{{ books.book_id }}">{{ books.book_title }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Nieko nėra.</p>
  {% endif %}


{% endblock %}